# RAiDER in Python

RAiDER can be called and used from with Python. 

In [1]:
# at the most basic level, can "import RAiDER"
import RAiDER

In [2]:
# we'll need some other basic libraries
import datetime
import pyproj
import xarray
import matplotlib

import numpy as np
import matplotlib.pyplot as plt

## Downloading weather model data
RAiDER provides access to multiple weather models through a consistent API. 
RAiDER will process the weather model data to a regular 3D cube and write the data to a NETCDF file that will be used later by the `tropo_delay` function to calculate delays at specified query points. 

In order to download weather model data, we need to instantiate a weather model object of the appropriate class. 

In [6]:
# We can print out the list of models currently implemented in RAiDER
# Note that some of these models require licenses etc. 
from RAiDER.models.allowed import ALLOWED_MODELS
print(ALLOWED_MODELS)

['ERA5', 'ERA5T', 'HRRR', 'GMAO', 'HRES', 'NCMR']


In [7]:
# The HRRR model from NOAA can be accessed for free
from RAiDER.models.hrrr import HRRR

To access weather model data, we need only to specify a datetime and a bounding box in South-North-West-East format

In [10]:
# First define datetime, and AOI
date_time = datetime.datetime(2018,11,13, 23, 0, 0)

# bounding box is given in SNWE format
ll_bounds = [36.8, 36.85, -76.15, -76.05]

In [12]:
print(date_time)
print(ll_bounds)

2018-11-13 23:00:00
[36.8, 36.85, -76.15, -76.05]


`prepareWeatherModel` is the function for accessing weather model data. 

In [15]:
from RAiDER.processWM import prepareWeatherModel

In [16]:
help(prepareWeatherModel)

Help on function prepareWeatherModel in module RAiDER.processWM:

prepareWeatherModel(weather_model, time=None, wmLoc: str = None, ll_bounds: List[float] = None, download_only: bool = False, makePlots: bool = False, force_download: bool = False) -> str
    Parse inputs to download and prepare a weather model grid for interpolation
    
    Args:
        weather_model: WeatherModel   - instantiated weather model object
        time: datetime                - Python datetime to request. Will be rounded to nearest available time
        wmLoc: str                    - file path to which to write weather model file(s)
        ll_bounds: list of float      - bounding box to download in [S, N, W, E] format
        download_only: bool           - False if preprocessing weather model data
        makePlots: bool               - whether to write debug plots
        force_download: bool          - True if you want to download even when the weather model exists
    
    Returns:
        str: file

Instantiate the weather model and then pass it to `prepareWeatherModel`

In [18]:
weather_model = HRRR()

In [19]:
# For the first example, we'll do a zenith calculation at the weather model grid nodes
prepareWeatherModel(weather_model, date_time, ll_bounds=ll_bounds, makePlots=True)

Extent of the weather model is (xmin, ymin, xmax, ymax):-76.46, 36.63, -75.72, 37.02
Extent of the input is (xmin, ymin, xmax, ymax): -76.15, 36.80, -76.05, 36.85


'/Users/jlmd9g/software/RAiDER-docs/notebooks/RAiDER_tutorial/weather_files/HRRR_2018_11_13_T23_00_00_37N_38N_77W_76W.nc'

You can look at the PDF files generated to see slices of the weather model variables at different heights. 

We can also load the weather model using xarray:

In [24]:
# we can get the name of the weather model file by passing the write directory to the 'out_file' method
weather_model_file = weather_model.out_file('weather_files')
ds = xarray.load_dataset(weather_model_file)

In [21]:
ds

<xarray.Dataset>
Dimensions:      (x: 19, y: 20, z: 145)
Coordinates:
  * x            (x) float64 1.862e+06 1.865e+06 ... 1.913e+06 1.916e+06
  * y            (y) float64 5.694e+03 8.694e+03 ... 5.969e+04 6.269e+04
  * z            (z) float32 -500.0 -300.0 -200.0 ... 7.458e+04 8.03e+04
Data variables:
    CRS          |S1 b''
    latitude     (z, y, x) float64 -3.403e+38 -3.403e+38 ... -3.403e+38
    longitude    (z, y, x) float64 -3.403e+38 -3.403e+38 ... -3.403e+38
    t            (z, y, x) float32 284.1 284.2 284.2 284.2 ... 207.2 207.2 207.2
    p            (z, y, x) float32 1.013e+05 1.013e+05 ... 5.337e+03 5.337e+03
    e            (z, y, x) float32 1.11e+03 1.107e+03 ... 0.06057 0.06064
    wet          (z, y, x) float32 52.49 52.31 52.31 ... 0.005358 0.005365
    hydro        (z, y, x) float32 276.6 276.6 276.6 276.5 ... 19.99 19.99 19.99
    wet_total    (z, y, x) float32 0.2615 0.2615 0.2616 0.2618 ... 0.0 0.0 0.0
    hydro_total  (z, y, x) float32 3.552 3.551 3.551 3.551 ... 0.0 0.0 0.0 0.0
Attributes:
    Conventions:   CF-1.6
    datetime:      2018_11_13T23_00_00
    date_created:  2022_12_10T21_35_57
    title:         Weather model data and delay calculations

"wet_total" and "hydro_total" are the zenith delays (ZTD) at the weather model grid nodes. 

We can now run the delay calculation using various input query points

## Delay calculation

The pre-processed weather model already has zenith delays calculated at the grid nodes, but if we want the delays at specific query points we need to use the `tropo_delay` function in RAiDER. 

In [22]:
from RAiDER.delay import tropo_delay

In [23]:
help(tropo_delay)

Help on function tropo_delay in module RAiDER.delay:

tropo_delay(dt, weather_model_file: str, aoi, los, height_levels: List[float] = None, out_proj: int | str = 4326, cube_spacing_m: int = None, look_dir: str = 'right')
    Calculate integrated delays on query points.
    
    Args:
        dt: Datetime                - Datetime object for determining when to calculate delays
        weather_model_File: string  - Name of the NETCDF file containing a pre-processed weather model
        aoi: AOI object             - AOI object
        los: LOS object             - LOS object
        height_levels: list         - (optional) list of height levels on which to calculate delays. Only needed for cube generation.
        out_proj: int,str           - (optional) EPSG code for output projection
        look_dir: str               - (optional) Satellite look direction. Only needed for slant delay calculation
        cube_spacing_m: int         - (optional) Horizontal spacing in meters when genera

We will need a few more objects for this delay calculation depending on the type of delays desired. 
The `weather_model_file` is the file path to the NETCDF file generated from `prepareWeatherModel`. 

## AOI objects
The AOI object is is one of several types depending on what is requested. 

In [1]:
# 1. basic data types and input parameters
from RAiDER.llreader import BoundingBox, StationFile # also available:  RasterRDR

In [29]:
aoi = BoundingBox(ll_bounds)
print(aoi.bounds())

[36.8, 36.85, -76.15, -76.05]


We can do much more with the AOI objects then just define a bounding box. 
For example, we can load lat/lon files or files containing GNSS station lists: 

In [2]:
test_aoi = StationFile('data/sample_gnss_list.csv')
print(test_aoi)

Several methods become available upon creation of the object

In [4]:
test_aoi.bounds()

[29.02655998900001, 38.999923395, -122.959307604, -113.010345532]

In [6]:
test_aoi.projection()

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

We can use the `readLL` and `readZ` methods to access the lat/lon and elevation values. If no elevation values are available from the data, a DEM will be downloaded on the fly. 

In [7]:
test_aoi.readLL()

(array([36.4291786 , 37.59498606, 34.1164069 , ..., 37.54305283,
        37.54302561, 37.55816598]),
 array([-120.26497691, -114.75908956, -117.09319198, ..., -122.01594425,
        -122.01589243, -117.49021941]))

In [8]:
test_aoi.readZ()

array([  56.5231551, 1713.2781038,  762.0717087, ...,   -3.5718802,
         -3.5279006, 1924.5517791])

## The LOS object

The LOS object defines the type of delay to calculate; can be zenith delays (ZTD), slant delays (STD) projected from the zenith delays, and slant delays (STD) integrated along the ray path. 

In [32]:
# "Conventional" refers to slant delays by projection
from RAiDER.losreader import Zenith, Conventional, Raytracing

In [33]:
los = Zenith()

In [39]:
los.is_Zenith()

True

If using the `Conventional` or `Raytracing` objects, an orbit file or look vector files should be supplied

In [40]:
los_ray = Raytracing('data/S1A_OPER_AUX_POEORB_OPOD_20181203T120749_V20181112T225942_20181114T005942.EOF', time=date_time)

In [41]:
los_ray.is_Zenith()

False

In [44]:
los_ray.ray_trace()

True

### ZTD calculation

Delay calculation in this case will be for a uniform cube at fixed height levels and horizontal spacing. 

In [45]:
# calculate ZTD 
ds,_ = tropo_delay(date_time, weather_model.out_file('weather_files'), aoi, los, height_levels=[0, 100, 500, 1000], cube_spacing_m=5000)

Output SNWE: [36.75, 36.85, -76.15, -76.0]
Output cube spacing: 0.05


Because we asked for a cube, the delays are returned as a single xarray Dataset. In other cases e.g. for rasters, wet and hydrostatic delays will be returned as two ndarrays. 

We can look at the output of the delay calculation in the Dataset

In [46]:
ds

<xarray.Dataset>
Dimensions:          (z: 4, y: 3, x: 5)
Coordinates:
  * x                (x) float64 -76.15 -76.1 -76.05 -76.0 -75.95
  * y                (y) float64 36.85 36.8 36.75
  * z                (z) int64 0 100 500 1000
Data variables:
    wet              (z, y, x) float64 0.2241 0.2271 0.2274 ... 0.1877 0.1885
    hydro            (z, y, x) float64 3.41 3.409 3.409 ... 3.145 3.145 3.145
    cube_projection  int64 0
Attributes:
    Conventions:     CF-1.7
    title:           RAiDER geo cube
    source:          HRRR_2018_11_13_T23_00_00_37N_38N_77W_76W.nc
    history:         2022-12-20 02:40:57.894186 RAiDER
    description:     RAiDER geo cube - zenith
    reference_time:  2018-11-13 23:00:00

We can look at the output shape etc.

In [59]:
print(ds['wet'].shape)
print(ds['wet'].values.mean())
print(ds['wet'].attrs)

(4, 3, 5)
0.21183146750972442
{'units': 'm', 'description': 'wet zenith delay', 'grid_mapping': 'cube_projection'}


Projection information is maintained in the dataset

In [60]:
print(ds.cube_projection)

<xarray.DataArray 'cube_projection' ()>
array(0)
Attributes:
    crs_wkt:                      GEOGCRS["WGS 84",ENSEMBLE["World Geodetic S...
    semi_major_axis:              6378137.0
    semi_minor_axis:              6356752.314245179
    inverse_flattening:           298.257223563
    reference_ellipsoid_name:     WGS 84
    longitude_of_prime_meridian:  0.0
    prime_meridian_name:          Greenwich
    geographic_crs_name:          WGS 84
    grid_mapping_name:            latitude_longitude


### Raytracing calculation

In [61]:
ds,_ = tropo_delay(date_time, 'weather_files/HRRR_2018_11_13_T12_00_00_37N_38N_77W_76W.nc', aoi, los_ray, height_levels=[0, 100, 500, 1000])

Output SNWE: [36.78, 36.87, -76.17, -76.05]
Output cube spacing: 0.03
Look direction: right
Processing slice 1 / 4: 0
Processing slice 2 / 4: 100
Processing slice 3 / 4: 500
Processing slice 4 / 4: 1000


In [21]:
ds

<xarray.Dataset>
Dimensions:          (z: 4, y: 4, x: 6)
Coordinates:
  * x                (x) float64 -76.17 -76.14 -76.11 -76.08 -76.05 -76.02
  * y                (y) float64 36.87 36.84 36.81 36.78
  * z                (z) int64 0 100 500 1000
Data variables:
    wet              (z, y, x) float64 0.4313 0.4318 0.4333 ... 0.328 0.3279
    hydro            (z, y, x) float64 3.344 3.44 3.523 ... 2.381 2.565 2.692
    cube_projection  int64 0
Attributes:
    Conventions:     CF-1.7
    title:           RAiDER geo cube
    source:          HRRR_2018_11_13_T12_00_00_37N_38N_77W_76W.nc
    history:         2022-12-11 03:36:17.396004 RAiDER
    description:     RAiDER geo cube - slant - raytracing
    reference_time:  2018-11-13 23:00:00

In [65]:
# Look at the output
print(ds['wet'].shape)
print(ds['hydro'].shape)
print(ds['wet'].values.mean())
print(ds['hydro'].values.mean())
print(ds['wet'].attrs)

(4, 4, 6)
(4, 4, 6)
0.39695660854055426
3.0515329152900406
{'units': 'm', 'description': 'wet slant - raytracing delay', 'grid_mapping': 'cube_projection'}
